name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ labeled ]
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ghcr.io/${{ secrets.USERNAME }}/test
        tags: latest
        registry: ghcr.io
        dockerfile: Dockerfile
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.ACCESS_TOKEN }}
